<?php

use App\Models\Movie;
use Illuminate\Database\Seeder;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $movies = [
            [
                "title" => "Wonder Woman 1984 (2020)",
                "description" => "Fast forward to the 1980s as Wonder Woman’s next big screen adventure finds her facing two all-new foes: Max Lord and The Cheetah. With director Patty Jenkins back at the helm and Gal Gadot returning in the title role, Wonder Woman 1984 is Warner Bros. Pictures’ follow up to the DC Super Hero’s first outing, 2017’s record-breaking Wonder Woman, which took in $822 million at the worldwide box office. The film also stars Chris Pine as Steve Trevor, Kristen Wiig as The Cheetah, Pedro Pascal as Max Lord, Robin Wright as Antiope and Connie Nielsen as Hippolyta. Charles Roven, Deborah Snyder, Zack Snyder, Patty Jenkins, Gal Gadot and Stephen Jones are producing the film. Rebecca Steel Roven Oakley, Richard Suckle, Marianne Jenkins, Geoff Johns, Walter Hamada, Chantal Nong Vo and Wesley Coller are the executive producers. Patty Jenkins directed from a screenplay she wrote with Geoff Johns & David Callaham, story by Jenkins & Johns, based on characters from DC. Joining the director behind the scenes are several members of her Wonder Woman team, including director of photography Matthew Jensen, Oscar-nominated production designer Aline Bonetto (Amélie), and Oscar-winning costume designer Lindy Hemming (Topsy-Turvy). Oscar-nominated editor Richard Pearson (United 93) is cutting the film. The music is by Oscar-winning composer Hans Zimmer (Dunkirk, The Lion King). Warner Bros. Pictures Presents an Atlas Entertainment/Stone Quarry Production, a Patty Jenkins Film, Wonder Woman 1984.",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2020/12/Movies-Thumb_WW84_HelmetArt_5fca9741c15786.50981449.jpg?itok=uOId2E-P",
                "cover" => "https://www.dccomics.com/sites/default/files/Movies-Gallery_WW84_05_5e4f3d2424ca61.78478943.jpg",
                "director" => "Patty Jenkins",
                "genre" => "Action, Adventure"
            ],
            [
                "title" => "Birds of Prey (2020)",
                "description" => "Birds of Prey (And the Fantabulous Emancipation of One Harley Quinn) is a twisted tale told by Harley herself, as only Harley can tell it. When Gotham’s most nefariously narcissistic villain, Roman Sionis, and his zealous right-hand, Zsasz, put a target on a young girl named Cass, the city is turned upside down looking for her. Harley, Huntress, Black Canary and Renee Montoya’s paths collide, and the unlikely foursome have no choice but to team up to take Roman down. In the Warner Bros. Pictures film, Margot Robbie (I, Tonya) returns as Harley Quinn, alongside Mary Elizabeth Winstead (10 Cloverfield Lane, TV’s Fargo) as Huntress; Jurnee Smollett-Bell (HBO’s True Blood) as Black Canary; Rosie Perez (Fearless, Pitch Perfect 2) as Renee Montoya; Chris Messina (Argo, TV’s Sharp Objects) as Victor Zsasz; and Ewan McGregor (Stephen King’s Doctor Sleep, the Trainspotting films) as Roman Sionis. Newcomer Ella Jay Basco also stars as Cassandra “Cass” Cain in her feature film debut. Directed by Cathy Yan (Dead Pigs) from a script by Christina Hodson (Bumblebee), the film is based on characters from DC. Robbie also produced, alongside Bryan Unkeless and Sue Kroll. The film’s executive producers are Walter Hamada, Galen Vaisman, Geoff Johns, Hans Ritter and David Ayer. Joining Yan behind the scenes was a creative team comprised of director of photography Matthew Libatique (A Star Is Born, Venom); production designer K.K. Barrett (Her); editor Jay Cassidy (American Hustle, Silver Linings Playbook) and editor Evan Schiff (John Wick Chapters 2 & 3); and costume designer Erin Benach (A Star Is Born). The music is by Daniel Pemberton (Spider-Man: Into the Spider-Verse). Warner Bros. Pictures Presents a LuckyChap Entertainment Production, a Clubhouse Pictures Production, a Kroll & Co. Entertainment Production, Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn). Opening in theaters and IMAX nationwide on February 7, 2020, the film will be distributed by Warner Bros. Pictures.",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2019/12/Movies-Thumb_BoP__5df1b6165d38c7.32399605.jpg?itok=GDxnx3Rp",
                "cover" => "https://www.dccomics.com/sites/default/files/Movies-Gallery_BoP_01_5df1aea454ddc5.25066467.jpg",
                "director" => "Cathy Yan",
                "genre" => "Action, Adventure"
            ],
            [
                "title" => "Joker (2019)",
                "description" => "Director Todd Phillips' Joker centers around the iconic arch nemesis and is an original, standalone fictional story not seen before on the big screen. Phillips’ exploration of Arthur Fleck, who is indelibly portrayed by Joaquin Phoenix, is of a man struggling to find his way in Gotham’s fractured society. A clown-for-hire by day, he aspires to be a stand-up comic at night…but finds the joke always seems to be on him. Caught in a cyclical existence between apathy and cruelty, Arthur makes one bad decision that brings about a chain reaction of escalating events in this gritty character study. Three-time Oscar nominee Phoenix (The Master, Walk the Line, Gladiator) stars in the titular role alongside Oscar winner Robert De Niro (Raging Bull, The Godfather: Part II) as Franklin. The film also stars Zazie Beetz (Deadpool 2), Frances Conroy (TV’s American Horror Story, Hulu’s Castle Rock), Marc Maron (TV’s Maron, GLOW), Bill Camp (Red Sparrow, Molly’s Game), Glenn Fleshler (TV’s Billions, Barry), Shea Whigham (First Man, Kong: Skull Island), Brett Cullen (42, Netflix’s Narcos), Douglas Hodge (Red Sparrow, TV’s Penny Dreadful) and Josh Pais (upcoming Motherless Brooklyn, Going in Style). Oscar nominee Phillips (Borat, The Hangover trilogy) directs from a screenplay he co-wrote with Oscar-nominated writer Scott Silver (The Fighter), based on characters from DC. The film is produced by Phillips and Oscar nominee Bradley Cooper (A Star Is Born, American Sniper) under their Joint Effort banner, and Oscar nominee Emma Tillinger Koskoff (The Wolf of Wall Street). It is executive produced by Michael E. Uslan, Walter Hamada, Aaron L. Gilbert, Joseph Garner, Richard Baratta, and Bruce Berman. Behind the scenes, Phillips is joined by director of photography Lawrence Sher (Godzilla: King of the Monsters, The Hangover trilogy), production designer Mark Friedberg (Selma, The Amazing Spider-Man 2), editor Jeff Groth (War Dogs, The Hangover Part III), and Oscar-winning costume designer Mark Bridges (Phantom Thread, The Artist). The music is by Hildur Guðnadóttir (Sicario: Day of the Soldado).",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2019/08/Movies-Thumb_TheJoker_20190828_5d66fba5ad5239.73009138.jpg?itok=P42Xo8_0",
                "cover" => "https://www.dccomics.com/sites/default/files/Movies-Gallery_TheJoker_12470_5d802dc52aa643.43482512.jpg",
                "director" => "Todd Phillips",
                "genre" => "Crime & Gangster, Drama"
            ],
            [
                "title" => "Zack Snyder's Justice League (2021)",
                "description" => "In Zack Snyder's Justice League, determined to ensure Superman’s (Henry Cavill) ultimate sacrifice was not in vain, Bruce Wayne (Ben Affleck) aligns forces with Diana Prince (Gal Gadot) with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions. The task proves more difficult than Bruce imagined, as each of the recruits must face the demons of their own pasts to transcend that which has held them back, allowing them to come together, finally forming an unprecedented league of heroes. Now united, Batman (Affleck), Wonder Woman (Gadot), Aquaman (Jason Momoa), Cyborg (Ray Fisher) and The Flash (Ezra Miller) may be too late to save the planet from Steppenwolf, DeSaad and Darkseid and their dreadful intentions.",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2021/03/Movies-Thumb_ZackSnyderJusticeLeague_Keyart_603e9e717fed30.39358315.jpg?itok=nb91luZH",
                "cover" => "https://www.dccomics.com/sites/default/files/Movies-Gallery_ZackSnyderJusticeLeague_FilmCans_603e9c8be6b933.67825270.jpg",
                "director" => "Zack Snyder",
                "genre" => "Action, Adventure"
            ],
            [
                "title" => "The Batman (2022)",
                "description" => "From Warner Bros. Pictures comes Matt Reeves’ The Batman, starring Robert Pattinson in the dual role of Gotham City’s vigilante detective and his alter ego, reclusive billionaire Bruce Wayne. Starring alongside Pattinson (Tenet, The Lighthouse) as Gotham’s famous and infamous cast of characters are Zoë Kravitz (Big Little Lies, Fantastic Beasts: The Crimes of Grindelwald) as Selina Kyle; Paul Dano (Love & Mercy, 12 Years a Slave) as Edward Nashton; Jeffrey Wright (No Time to Die, Westworld) as the GCPD’s James Gordon; John Turturro (the Transformers films, The Plot Against America) as Carmine Falcone; Peter Sarsgaard (The Magnificent Seven, Interrogation) as Gotham D.A. Gil Colson; Jayme Lawson (Farewell Amor) as mayoral candidate Bella Reál; with Andy Serkis (the Planet of the Apes films, Black Panther) as Alfred; and Colin Farrell (The Gentlemen, Fantastic Beasts and Where to Find Them) as Oswald Cobblepot. Reeves (the Planet of the Apes franchise) directed from a screenplay by Reeves & Peter Craig, based on characters from DC. Batman was created by Bob Kane with Bill Finger. Dylan Clark (the Planet of the Apes films) and Reeves produced the film, with Michael E. Uslan, Walter Hamada, Chantal Nong Vo and Simon Emanuel serving as executive producers. The director’s behind-the-scenes creative team included Oscar-nominated director of photography Greig Fraser (Dune, Lion); Reeves’ Planet of the Apes production designer, James Chinlund, and editor, William Hoy; editor Tyler Nelson (Rememory); and Oscar-winning costume designer Jacqueline Durran (1917, Little Women, Anna Karenina). The music is by Oscar-winning composer Michael Giacchino (the current Spider-Man, Jurassic World and Star Wars films, Up). Warner Bros. Pictures Presents a 6th & Idaho/Dylan Clark Productions Production, a Matt Reeves Film, The Batman. The film is set to open in theaters March 4, 2022 and will be distributed worldwide by Warner Bros. Pictures.",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2021/11/Movies-Thumb_TheBatman_6185f30b435517.69951535.jpg?itok=3pDyQjln",
                "cover" => "https://www.dccomics.com/sites/default/files/Movies-Gallery_TheBatman_TBM-59313r_61e89f92d88586.12634193.jpg",
                "director" => "Matt Reeves",
                "genre" => "Action, Adventure"
            ],
            [
                "title" => "Injustice (2021)",
                "description" => "An unthinkable tragedy propels Superman into a dangerous new mindset, ultimately pitting Justice League members against each other in Injustice, an all-new DC Animated Movie. Inspired by Injustice: Gods Among Us, NetherRealm Studios’ popular video game, and the best-selling DC graphic novel based on the video game, Injustice: Gods Among Us: Year One by Tom Taylor, the animated film Injustice finds an alternate world gone mad—where the Joker has duped Superman into killing Lois Lane, sending the Man of Steel on a deadly rampage. Unhinged, Superman decides to take control of the Earth for humanity’s own good. Determined to stop him, Batman creates a team of like-minded, freedom-fighting heroes. But when superheroes go to war, can the world survive?",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2021/10/Movies-Thumb_Injustice_6168b61f9dac20.81521934.jpg?itok=GsH1dFJn",
                "cover" => "https://www.dccomics.com/sites/default/files/Movies-Gallery_Injustice_IJST_CreativeStill_20_300dpi_6168b4c47e1db6.35592221.jpg",
                "director" => "Matt Peters",
                "genre" => "Action, Adventure"
            ],
            [
                "title" => "The Suicide Squad (2021)",
                "description" => "Welcome to hell—a.k.a. Belle Reve, the prison with the highest mortality rate in the US of A. Where the worst Super-Villains are kept and where they will do anything to get out—even join the super-secret, super-shady Task Force X. Today’s do-or-die assignment? Assemble a collection of cons, including Bloodsport, Peacemaker, Captain Boomerang, Ratcatcher 2, Savant, King Shark, Blackguard, Javelin and everyone’s favorite psycho, Harley Quinn. Then arm them heavily and drop them (literally) on the remote, enemy-infused island of Corto Maltese. Trekking through a jungle teeming with militant adversaries and guerrilla forces at every turn, the Squad is on a search-and-destroy mission with only Colonel Rick Flag on the ground to make them behave…and Amanda Waller’s government techies in their ears, tracking their every movement. And as always, one wrong move and they’re dead (whether at the hands of their opponents, a teammate, or Waller herself). If anyone’s laying down bets, the smart money is against them—all of them. The film stars Margot Robbie (Birds of Prey, Bombshell), Idris Elba (Avengers: Infinity War), John Cena (upcoming HBO Max series Peacemaker, Bumblebee), Joel Kinnaman (Suicide Squad), Jai Courtney (the Divergent franchise), Peter Capaldi (World War Z, BBC’s Doctor Who ), David Dastmalchian (upcoming Dune, Ant-Man and the Wasp), Daniela Melchior (Parque Mayer), Michael Rooker (the Guardians of the Galaxy films), Alice Braga (Elysium), Pete Davidson (The King of Staten Island, TV’s Saturday Night Live), Joaquín Cosio (Spider-Man: Into the Spider-Verse, TV’s Narcos: Mexico), Juan Diego Botto (The Europeans), Storm Reid (The Invisible Man, A Wrinkle in Time, Euphoria), Nathan Fillion (Guardians of the Galaxy, TV’s The Rookie), Steve Agee (Brightburn, Guardians of the Galaxy Vol. 2), Sean Gunn (the Guardians of the Galaxy films, the Avengers films), Mayling Ng (Wonder Woman), Flula Borg (Ralph Breaks the Internet), Jennifer Holland (Brightburn, upcoming HBO Max series Peacemaker) and Tinashe Kajese (TV’s Valor, The Inspectors), with Sylvester Stallone (the Rocky, Rambo and Expendables franchises), and Viola Davis (Ma Rainey’s Black Bottom, Suicide Squad).",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2021/07/Movies-Thumb_TheSuicideSquad2021_july_60e4812d558cd9.83560586.jpg?itok=Jyp28suI",
                "cover" => "https://www.dccomics.com/sites/default/files/Movies-Gallery_TheSuicideSquad2021_source-16334712a7eab4ebce104bad9ecc55c405320bafmaster_6066424058b7f2.71342019.jpg",
                "director" => "James Gunn",
                "genre" => "Action, Adventure"
            ],
            [
                "title" => "Shazam! (2019)",
                "description" => "David F. Sandberg (Annabelle: Creation) directs New Line Cinema’s Shazam!, the origin story that stars Zachary Levi (TV’s Chuck) as the titular DC Super Hero, along with Asher Angel (TV’s Andi Mack) as Billy Batson, and Mark Strong (the Kingsman movies) in the role of Super-Villain Dr. Thaddeus Sivana. Peter Safran (upcoming Aquaman, The Conjuring and Annabelle films) serves as the film’s producer. We all have a superhero inside us, it just takes a bit of magic to bring it out. In Billy Batson’s (Angel) case, by shouting out one word—SHAZAM!—this streetwise 14-year-old foster kid can turn into the adult Super Hero Shazam (Levi), courtesy of an ancient wizard. Still a kid at heart—inside a ripped, godlike body—Shazam revels in this adult version of himself by doing what any teen would do with superpowers: have fun with them! Can he fly? Does he have X-ray vision? Can he shoot lightning out of his hands? Can he skip his social studies test? Shazam sets out to test the limits of his abilities with the joyful recklessness of a child. But he’ll need to master these powers quickly in order to fight the deadly forces of evil controlled by Dr. Thaddeus Sivana (Strong). Shazam! also stars Jack Dylan Grazer (IT) as Billy’s best friend and ultimate superhero enthusiast, Freddy, part of the foster family that includes Mary, played by Grace Fulton (Annabelle: Creation); Darla, played by Faithe Herman (TV’s This is Us); Eugene, played by Ian Chen (TV’s Fresh Off the Boat); and Pedro, played by Jovan Armand (TV’s Hawaii Five-O). Cooper Andrews (TV’s The Walking Dead) and Marta Milans (TV’s Killer Women) play foster parents Victor and Rosa Vasquez, with Oscar nominee Djimon Hounsou (Blood Diamond) as the Wizard. Firmly set in the DC universe but with his own distinctly fun, family-centric tone, the screenplay is by Henry Gayden, story by Gayden and Darren Lemke. Shazam was created by Bill Parker and C.C. Beck. Christopher Godsick, Jeffrey Chernov, Dwayne Johnson, Dany Garcia and Hiram Garcia serve as executive producers.",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2019/03/Movies-Thumb_Shazam20190313_5c8934a6c8f4c0.03036534.jpg?itok=4ldOIBGE",
                "cover" => "https://www.dccomics.com/sites/default/files/Movies-Gallery_Shazam2019_SHZM-TRLR-002_5c8938b887bb93.81757603.jpg",
                "director" => "David F. Sandberg",
                "genre" => "Action, Adventure"
            ],
            [
                "title" => "Batman: Gotham By Gaslight (2018)",
                "description" => "Inspired by the landmark one-shot Elseworlds tale by Brian Augustyn and Mike Mignola, Batman: Gotham By Gaslight takes place at the turn of the century as America’s continued industrial revolution is to be showcased at a World’s Fair hosted by Gotham City. But while the world prepares to witness the glittery glory of Gotham’s technological advances, there is a killer loose in the city’s darkest shadows. Preying on the city’s women, this killer is as precise as he is cruel. As Police Commissioner James Gordon tries to calm the fears of Gotham’s citizens regarding the butcher called Jack the Ripper, the masked vigilante Batman enacts his own detective work—with the help of confident, capable Selina Kyle—to stop the Ripper’s murderous spree. Witness a world in flames as the notorious serial killer’s controlled savagery meets the calculated stealth of the Dark Knight.",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2018/01/Movies-Thumb_BMGothamByGaslight__5a5fd4e68c8dd2.63798786.jpg?itok=_lZgit2E",
                "cover" => "https://www.dccomics.com/sites/default/files/Movies-Gallery_BMGothamByGaslight_01_5a5fd46c51da93.09674074.jpg",
                "director" => "Sam Liu",
                "genre" => "Action, Adventure"
            ],
            [
                "title" => "Aquaman (2018)",
                "description" => "From Warner Bros. Pictures and director James Wan comes an action-packed adventure that spans the vast, visually breathtaking underwater world of the seven seas, Aquaman, starring Jason Momoa in the title role. The film reveals the origin story of half-human, half-Atlantean Arthur Curry and takes him on the journey of his lifetime—one that will not only force him to face who he really is, but to discover if he is worthy of who he was born to be…a king. The film also stars Amber Heard (Justice League, Magic Mike XXL) as Mera, a fierce warrior and Aquaman’s ally throughout his journey; Oscar nominee Willem Dafoe (Platoon, Spider-Man 2) as Vulko, council to the Atlantean throne; Patrick Wilson (The Conjuring films, Watchmen) as Orm/Ocean Master, the present King of Atlantis; Dolph Lundgren (The Expendables films), King of the Atlantean tribe Xebel; Yahya Abdul-Mateen II (upcoming Baywatch, Netflix’s The Get Down) as the vengeful Black Manta; and Oscar winner Nicole Kidman (The Hours, Lion) as Arthur’s mom, Atlanna; as well as Ludi Lin (Power Rangers) as Captain Murk, Atlantean Commando; and Temuera Morrison (Star Wars: Episode II – Attack of the Clones, Green Lantern) as Arthur’s dad, Tom Curry. Wan directs from a screenplay by David Leslie Johnson-McGoldrick (The Conjuring 2) and Will Beall (Gangster Squad, TV’s Training Day), story by Geoff Johns & James Wan and Will Beall, based on characters from DC, Aquaman created by Paul Norris and Mort Weisinger. The film is produced by Peter Safran and Rob Cowan, with Deborah Snyder, Zack Snyder, Jon Berg, Geoff Johns and Walter Hamada serving as executive producers. Wan’s team behind the scenes includes such frequent collaborators as Oscar-nominated director of photography Don Burgess (The Conjuring 2, Forrest Gump), his five-time editor Kirk Morri (The Conjuring films, Furious 7, the Insidious films), and production designer Bill Brzeski (Furious 7). They are joined by costume designer Kym Barrett (The Matrix trilogy, The Amazing Spider-Man) and composer Rupert Gregson-Williams (Wonder Woman). Warner Bros. Pictures Presents a Safran Company Production, a James Waan Film, Aquaman. The film is set to hit theaters on December 21, 2018 in 3D and 2D and IMAX, and will be distributed worldwide by Warner Bros. Pictures, a Warner Bros. Entertainment Company.",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2018/11/Movies-Thumb_Aquaman2018_single_5bedc81a90d565.98093378.jpg?itok=tAcliKYZ",
                "cover" => "https://www.dccomics.com/sites/default/files/Movies-Gallery_Aquaman2018_Duo_5bedc13e7463a3.36467747.jpg",
                "director" => "James Wan",
                "genre" => "Action, Adventure"
            ],
            [
                "title" => "Justice League (2017)",
                "description" => "Fueled by his restored faith in humanity and inspired by Superman’s selfless act, Bruce Wayne enlists the help of his newfound ally, Diana Prince, to face an even greater enemy.  Together, Batman and Wonder Woman work quickly to find and recruit a team of metahumans to stand against this newly awakened threat.  But despite the formation of this unprecedented league of heroes—Batman, Wonder Woman, Aquaman, Cyborg and The Flash—it may already be too late to save the planet from an assault of catastrophic proportions. Directed by Zack Snyder, this marks the big screen debut of the Justice League, featuring an all-star lineup: Ben Affleck, Henry Cavill, Gal Gadot, Jason Momoa, Ezra Miller and Ray Fisher.",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2017/11/KeyarJL_TheLeague_Keyart_5a206235e32cc1.07186227.jpg?itok=2LeEVW2X",
                "cover" => "https://www.dccomics.com/sites/default/files/JL-FP-0132_master_gallery_5a04bbdfdbe525.77101583.jpg",
                "director" => "Zack Snyder",
                "genre" => "Action, Adventure"
            ],
            [
                "title" => "Man of Steel (2013)",
                "description" => "A young boy learns that he has extraordinary powers and is not of this Earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind. The film also stars four-time Oscar® nominee Amy Adams (“The Master”) as Daily Planet journalist Lois Lane, and Oscar® nominee Laurence Fishburne (“What’s Love Got to Do with It”) as her editor-in-chief, Perry White. Starring as Clark Kent’s adoptive parents, Martha and Jonathan Kent, are Oscar® nominee Diane Lane (“Unfaithful”) and Academy Award® winner Kevin Costner (“Dances with Wolves”). Squaring off against the superhero are two other surviving Kryptonians, the villainous General Zod, played by Oscar® nominee Michael Shannon (“Revolutionary Road”), and Faora, Zod’s evil partner, played by Antje Traue (upcoming “The Seventh Son”). Also from Superman’s native Krypton are Lara Lor-Van, Superman’s mother, played by Ayelet Zurer (“Angels and Demons”), and Superman’s father, Jor-El, portrayed by Academy Award® winner Russell Crowe (“Gladiator”). Rounding out the cast are Christopher Meloni (“42”) as U.S. military man Colonel Hardy, Harry Lennix (“State of Play”) as General Swanwick, Michael Kelly (“The Adjustment Bureau”) as Steve Lombard, and Richard Schiff (TV’s “The West Wing”) as Dr. Emil Hamilton. “Man of Steel” is being produced by Charles Roven, Christopher Nolan, Emma Thomas and Deborah Snyder. The screenplay was written by David S. Goyer from a story by Goyer & Nolan, based upon Superman characters created by Jerry Siegel & Joe Shuster and published by DC Entertainment. Thomas Tull, Lloyd Phillips and Jon Peters are serving as executive producers.",
                "thumb" => "https://www.dccomics.com/sites/default/files/styles/covers192x291/public/movie-covers/2013/12/manofsteel_thumb_192x291_52ab977d243284.01494825.jpg?itok=uuGgC2Iu",
                "cover" => "https://www.dccomics.com/sites/default/files/GalleryMovies_1920x1080_ManOfSteel_552586ca9859f8.59715358.jpg",
                "director" => "Zack Snyder",
                "genre" => "Action, Adventure"
            ]
        ];

        foreach ($movies as $movie) {
            $_movie = new Movie();
            $_movie->title = $movie['title'];
            $_movie->description = $movie['description'];
            $_movie->thumb = $movie['thumb'];
            $_movie->cover = $movie['cover'];
            $_movie->director = $movie['director'];
            $_movie->genre = $movie['genre'];
            $_movie->save();
        }
    }
}
